### PR TITLE
add CRAN check badge

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by maelle** [comment]
Both CI checks seem to be due to a connection failure cf e.g. https://travis-ci.org/r-hub/rversions/jobs/527180735#L1028

Should tests be actually skipped on CRAN?

**Comment by gaborcsardi** [comment]
> Both CI checks seem to be due to a connection failure

oh, Travis (and Appveyor?) banned from CRAN?

**Comment by gaborcsardi** [comment]
> Should tests be actually skipped on CRAN?

I guess we would need to skip them on the CIs.....

**Comment by gaborcsardi** [comment]
OK, here's what we'll do. We add a new env var `R_RVERSIONS_CRAN_URL` and use that in the code. Defaults to cran.r-project.org. In the CIs we'll set it to `cloud.r-project.org`.

**Comment by gaborcsardi** [comment]
But feel free to ignore these failures for now.

**Review by gaborcsardi — APPROVED** [review]

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
